# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!
######################################################################
# Developer :     Ayush Bairagi & dheeraj satokia
# E-mail:         abairagi311@gmail.com
# Github profile: github.com/ayush3298
# project:
# ####################################################################

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1158, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.articleByLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.articleByLabel.setFont(font)
        self.articleByLabel.setObjectName("articleByLabel")
        self.horizontalLayout_2.addWidget(self.articleByLabel)
        self.followBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.followBtn.sizePolicy().hasHeightForWidth())
        self.followBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.txtSearch = QtWidgets.QLineEdit(MainWindow)
        self.txtSearch.setGeometry(QtCore.QRect(450, 10, 191, 27))
        self.txtSearch.setObjectName("txtSearch")
        self.btnSearch = QtWidgets.QPushButton(MainWindow)
        self.btnSearch.setGeometry(QtCore.QRect(650, 10, 71, 27))
        self.btnSearch.setObjectName("btnSearch")
        self.btnSearch.setText('Search')



        self.followBtn.setFont(font)
        self.followBtn.setIconSize(QtCore.QSize(24, 24))
        self.followBtn.setObjectName("followBtn")
        self.horizontalLayout_2.addWidget(self.followBtn)
        self.refreshBtn = QtWidgets.QPushButton(self.centralwidget)
        self.refreshBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshBtn.sizePolicy().hasHeightForWidth())
        self.refreshBtn.setSizePolicy(sizePolicy)
        self.refreshBtn.setToolTip("Refrash article")
        self.refreshBtn.setWhatsThis("")
        self.refreshBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshBtn.setIcon(icon)
        self.refreshBtn.setIconSize(QtCore.QSize(18, 18))
        self.refreshBtn.setCheckable(False)
        self.refreshBtn.setObjectName("refreshBtn")
        self.horizontalLayout_2.addWidget(self.refreshBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.followScroll = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.followScroll.sizePolicy().hasHeightForWidth())
        self.followScroll.setSizePolicy(sizePolicy)
        self.followScroll.setWidgetResizable(True)
        self.followScroll.setObjectName("followScroll")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 241, 245))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.followScroll.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout.addWidget(self.followScroll)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sourcelistLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourcelistLabel.sizePolicy().hasHeightForWidth())
        self.sourcelistLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sourcelistLabel.setFont(font)
        self.sourcelistLabel.setObjectName("sourcelistLabel")
        self.horizontalLayout.addWidget(self.sourcelistLabel)
        self.categoryCombobox = QtWidgets.QComboBox(self.centralwidget)
        self.categoryCombobox.setObjectName("categoryCombobox")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.categoryCombobox.addItem("")
        self.horizontalLayout.addWidget(self.categoryCombobox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sourcesScroll = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourcesScroll.sizePolicy().hasHeightForWidth())
        self.sourcesScroll.setSizePolicy(sizePolicy)
        self.sourcesScroll.setWidgetResizable(True)
        self.sourcesScroll.setObjectName("sourcesScroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 241, 245))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.sourcesScroll.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.sourcesScroll)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.articleScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.articleScroll.setWidgetResizable(True)
        self.articleScroll.setObjectName("articleScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 887, 753))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.articleScroll.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.articleScroll, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "News"))
        self.articleByLabel.setText(_translate("MainWindow", "Articles by: "))
        self.followBtn.setText(_translate("MainWindow", "Follow"))
        self.refreshBtn.setStatusTip(_translate("MainWindow", "Refresh articles"))
        self.sourcelistLabel.setText(_translate("MainWindow", "Source list"))
        self.categoryCombobox.setItemText(0, _translate("MainWindow", "all"))
        self.categoryCombobox.setItemText(1, _translate("MainWindow", "general"))
        self.categoryCombobox.setItemText(2, _translate("MainWindow", "entertainment"))
        self.categoryCombobox.setItemText(3, _translate("MainWindow", "gaming"))
        self.categoryCombobox.setItemText(4, _translate("MainWindow", "business"))
        self.categoryCombobox.setItemText(5, _translate("MainWindow", "politics"))
        self.categoryCombobox.setItemText(6, _translate("MainWindow", "music"))
        self.categoryCombobox.setItemText(7, _translate("MainWindow", "science-and-nature"))
        self.categoryCombobox.setItemText(8, _translate("MainWindow", "sport"))
        self.categoryCombobox.setItemText(9, _translate("MainWindow", "technology"))
        self.label.setText(_translate("MainWindow", "Followed"))

